<?php
// $Id$
// by Jeff Robbins

/**
 * @file
 * Similar By Terms module displays a block with similar content
 * based on taxonomy terms.
 */

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function similarterms_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#similarterms":
      $output = '<p>'.  t("Displays a block with similar content based on taxonomy terms.") .'</p>';
      break;
  }
  return $output;
} // function similarterms_help

/**
 * Valid permissions for this module
 * @return array An array of valid permissions for the onthisdate module
 */
function similarterms_perm() {
  return array('access similarterms content', 'administer similarterms content');
} // function similarterms_perm()


/**
 * Implementation of hook_block().
 */
function similarterms_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[]['info'] = t('Similar entries from ANY vocabulary.');
    foreach (taxonomy_get_vocabularies() as $v) {
      // this only makes sense for multi-select vocabularies and free tagging
      if ($v->multiple || $v->tags) {
        $blocks[$v->vid]['info'] = t('Similar entries from the @vocab vocabulary.', array('@vocab' => $v->name));
      }
    }
    return $blocks;
  }
  else if ($op == 'configure') {
    $form['count'] = array(
      '#type' => 'textfield',
      '#title' => t('Item count'),
      '#default_value' => variable_get('simterms_count_'. $delta, 5),
      '#size' => 3,
      '#description' => t('The maximum number of similar items to display'),
    );
    //mimo addition to configuration to limit to same page type
    $types = array('0'=>'<none>','1'=>t('same as current'));
    $arrTypesObj = node_get_types();
    foreach($arrTypesObj as $type=>$obj) {
      $types[$type] = $obj->name;
    }
    $form['sametype'] = array(
      '#type' => 'select',
      '#title' => t('Content type limit'),
      '#default_value' => variable_get('simterms_sametype_'. $delta, false),
      '#options' => $types,
      '#description' => t('Limit to pages of this or these content type(s)'),
      '#multiple' => TRUE
    );
    return $form; 
  }
  else if ($op == 'save') {
    variable_set('simterms_count_'. $delta, $edit['count']); 
    variable_set('simterms_sametype_'. $delta, $edit['sametype']);
  }
  else if ($op == 'view') {
    if ($delta == 0) {
      $block['subject'] = t('Similar');
      $block['content'] = theme('similarterms', similarterms_list());
    }
    else {
      $block['subject'] = t('Similar');
      $block['content'] = theme('similarterms', similarterms_list($delta));
    }
    return $block;
  }
}

/**
 * Output the block
 *
 * @param $vid
 *   integer - vocabulary id, leave out to use ALL terms for this node
 * @param $nid
 *   integer - node id, leave out to use current page
 * @return
 *   an array of partial node objects (containing just the parts from the node table)
 */
function similarterms_list($vid = NULL, $nid = NULL) {
  if (is_null($nid) && (arg(0) == 'node' && is_numeric(arg(1)))) {
    $nid = arg(1);
  }
  $nodes = array();
  if (!is_null($nid)) {
    if (!is_null($vid)) {
      $terms = implode(',', array_keys(taxonomy_node_get_terms_by_vocabulary(node_load($nid), $vid)));
      $count = variable_get('simterms_count_'. $vid, 5);
    }
    else {
      $terms = implode(',', array_keys(taxonomy_node_get_terms(node_load($nid))));
      $count = variable_get('simterms_count_0', 5);
    }
    if (!empty($terms)) {
      $delta = $vid?$vid:0;
      $count = variable_get('simterms_count_'. $delta, 5);
      //past events
      $pasts = array();

      // mimo addition to load select only nodes of the same content type
      $types = variable_get('simterms_sametype_'.$delta, false);
      if(($types !== false) && is_array($types)) {
      	if($types[1]) {
      	  $nodeObj = node_load($nid);
      	  $types[1] = $nodeObj->type;
      	}
	$strTypes = "'" . implode("','",$types) . "'"; // couldnt find a solutin for IN %s problem and \' substi
        $result = db_query(
	  'SELECT n.nid, n.title, COUNT(n.nid) AS ncount
	    FROM {node} n
	    INNER JOIN {term_node} tn ON n.nid = tn.nid
	    WHERE tn.tid IN (%s)
	    AND n.type IN ('.$strTypes.')
	    AND n.nid != %d
	    AND n.status = 1
	    AND n.moderate = 0
	    GROUP BY n.nid, n.title, n.created
	    ORDER BY ncount DESC, n.created DESC
	    LIMIT %d',
        $terms, $nid, $count);
      } else {
        $result = db_query(
	  'SELECT n.nid, n.title, COUNT(n.nid) AS ncount
	    ROM {node} n
	    INNER JOIN {term_node} tn ON n.nid = tn.nid
	    WHERE tn.tid IN (%s)
	    AND n.nid != %d
	    AND n.status = 1
	    AND n.moderate = 0
	    GROUP BY n.nid, n.title, n.created
	    ORDER BY ncount DESC, n.created DESC
	    LIMIT %d',
	$terms, $nid, $count);
      }

      while ($r = db_fetch_object($result)) {
        $nodes[] = node_load($r->nid);
      }
    }
  }
  return $nodes;
}

/**
 * Theme function for similar block
 *
 */
function similarterms_theme() {
  return array(
    'similarterms' => array(
      'template'  => 'similarterms',
      'arguments' => array('items' => NULL),
       ),
  );
}
